//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectCEBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMERE
    {
        public decimal IDCAMERA { get; set; }
        public Nullable<decimal> IDUNITATICAZARE { get; set; }
        public string DENUMIRE { get; set; }
        public Nullable<decimal> CAPACITATE { get; set; }
        public string DISPONIBILITATE { get; set; }
    
        public virtual UNITATI_DE_CAZARE UNITATI_DE_CAZARE { get; set; }
    }
}
