//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectCEBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVIEW
    {
        public decimal IDREVIEW { get; set; }
        public Nullable<decimal> IDUNITATICAZARE { get; set; }
        public Nullable<decimal> IDCLIENTE { get; set; }
        public Nullable<decimal> RATING { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public string NUMEAUTOR { get; set; }
        public string DESCRIERE { get; set; }
    
        public virtual CLIENTI CLIENTI { get; set; }
        public virtual UNITATI_DE_CAZARE UNITATI_DE_CAZARE { get; set; }
    }
}
