//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectCEBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REZERVARI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REZERVARI()
        {
            this.CLIENTIs = new HashSet<CLIENTI>();
        }
    
        public decimal IDREZERVARI { get; set; }
        public Nullable<decimal> IDUNITATICAZARE { get; set; }
        public Nullable<System.DateTime> DATASOSIRE { get; set; }
        public Nullable<System.DateTime> DATAPLECARE { get; set; }
        public Nullable<decimal> NUMARPERSOANE { get; set; }
    
        public virtual UNITATI_DE_CAZARE UNITATI_DE_CAZARE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTI> CLIENTIs { get; set; }
    }
}
