//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectCEBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNITATI_DE_CAZARE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UNITATI_DE_CAZARE()
        {
            this.CAMEREs = new HashSet<CAMERE>();
            this.REVIEWs = new HashSet<REVIEW>();
            this.REZERVARIs = new HashSet<REZERVARI>();
            this.FACILITATIs = new HashSet<FACILITATI>();
            this.SERVICII_SUPLIMENTARE = new HashSet<SERVICII_SUPLIMENTARE>();
        }
    
        public decimal IDUNITATICAZARE { get; set; }
        public Nullable<decimal> IDCOMPLEXCAZARE { get; set; }
        public Nullable<decimal> IDTIPURIUNITATICAZARE { get; set; }
        public string NUME { get; set; }
        public string PRET { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAMERE> CAMEREs { get; set; }
        public virtual COMPLEX_CAZARE COMPLEX_CAZARE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REVIEW> REVIEWs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REZERVARI> REZERVARIs { get; set; }
        public virtual TIPURI_UNITATI_DE_CAZARE TIPURI_UNITATI_DE_CAZARE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACILITATI> FACILITATIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICII_SUPLIMENTARE> SERVICII_SUPLIMENTARE { get; set; }
    }
}
